GET http://localhost:3001/getProfiles HTTP/1.1
###

POST https://rocketproject2021.herokuapp.com/signup 
Content-Type: application/json

{
    "name": "nacho Perez",
    "country": "Argentina",
    "email": "nacho123@gmail.com",
    "institution":"Henry",
    "password": "nacho123"

}
###
POST https://rocketproject2021.herokuapp.com/signin
Content-Type: application/json

{
    
    "email": "nacho123@gmail.com",
    "password": "nacho123"

}
###
POST http://localhost:3001/islog 
Content-Type: application/json

{ 
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWVkZWU2M2E4MGYwMTNiMzg3NmRmNSIsImlhdCI6MTYzNzgwMjk3NX0.3WxjldnWv1VuNJSQaXzcyz5m4Mm30hhhAcQ1XGno5YU"
}
###
POST http://localhost:3001/Institution 
Content-Type: application/json

{
    "name": "Henryyyyy"
}
###
POST http://localhost:3001/filterUserByTable
Content-Type: application/json
{
table: 1
}
